services:
  - type: web
    name: event-registration-fastapi
    env: docker
    rootDirectory: backend
    envVars:
      - key: APP_NAME
        value: "Event Registration System"
      - key: ENVIRONMENT
        value: production
      - key: ALLOW_DUPLICATE_EMAIL
        value: "false"
      - key: LOCK_EDIT_AFTER_APPROVAL
        value: "true"
