import argparse
import time
from PIL import Image
import numpy as np

try:
    import onnxruntime as ort
except ImportError:
    print("Please pip install onnxruntime")
    exit(1)

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

def test_inference(model_path, image_path):
    print(f"Loading ONNX model from {model_path}...")
    
    try:
        session = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
    except Exception as e:
        print(f"Failed to load ONNX model: {e}")
        return
        
    input_name = session.get_inputs()[0].name
    
    print(f"Processing image {image_path}...")
    img = Image.open(image_path).convert("RGB")
    
    # YOLO classification preprocessing (Resize to 224x224, center crop, normalize to 0-1)
    img = img.resize((224, 224), Image.BILINEAR)
    
    # Convert to numpy and transpose to NCHW
    img_data = np.array(img).astype(np.float32) / 255.0
    img_data = np.transpose(img_data, (2, 0, 1))
    img_data = np.expand_dims(img_data, axis=0)
    
    print("Running inference...")
    start_time = time.time()
    outputs = session.run(None, {input_name: img_data})
    end_time = time.time()
    
    logits = outputs[0][0]
    probs = softmax(logits)
    
    print(f"\nInference completed in {(end_time - start_time) * 1000:.2f} ms")
    
    # Assume class 0 is non_receipt, class 1 is payment_receipt
    # NOTE: You must check the actual class order generated by YOLO during training
    # which is printed in outputs/receipt_classifier/args.yaml
    
    print("Raw output (logits):", logits)
    print("Probabilities:", probs)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test ONNX model inference.")
    parser.add_argument("--model", default="outputs/receipt_classifier/weights/best.onnx", help="Path to ONNX model")
    parser.add_argument("--image", required=True, help="Path to image to test")
    args = parser.parse_args()
    
    test_inference(args.model, args.image)
